version: "3"

services:
  postgres:
    image: "postgres:13.3"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ciconia
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5450:5432
    volumes:
      - ./data:/var/lib/postgresql/data/pgdata

volumes:
  pgdata:
    driver: local